### ISSUE TITLE
Update guidelines

### ISSUE THREAD

**Issue by kvmanohar22** [krssg-ssl/ssl-misc#1]
@annimesh2809 update the contributing guidelines
@kvmanohar22 setup travis

**Comment by annimesh2809** [comment]
@kvmanohar22 I think there is a repo already named as [ssl_common](https://github.com/krssg-ssl/ssl_common). Won't this cause any ambiguity? I think it would be better to rename it to something else. :smile:

**Comment by kvmanohar22** [comment]
Didn't notice that ! I will change it.

**Comment by kvmanohar22** [comment]
How about we have **RESOURCES.md**  something similar to [this](https://github.com/terryum/awesome-deep-learning-papers#contents) and organize the papers under different categories (path planning, tactics, plays etc) ? This would help a lot to look up and refer !

**Comment by annimesh2809** [comment]
Yes, let me add that!
